# fly.toml app configuration file generated for manage-my-payroll on 2023-07-28T15:09:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "manage-my-payroll"
primary_region = "ams"
console_command = "/rails/bin/rails console"

[[build.env]]
name = "SECRET_KEY_BASE"
value = "a78357628f11dcfe288ae2381a824caa59effc996baf3014c6c572f088699323e075398094601a150852bf2709c069b408be4fe533b0b416ec6a6ae778dd164b"

[deploy]
  release_command = "./bin/rails db:prepare"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
