databases:
  - name: postgres
    ipAllowList: []
    # databaseName: manage-my-payroll
    # user: manage-my-payroll
    plan: free

services:
  - type: web
    name: manage-my-payroll
    plan: free
    env: ruby
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: manage-my-payroll
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false